### ISSUE TITLE
running this directory on Azure Container Apps

### ISSUE THREAD

**Issue by Peet0103** [dteck/Mediawiki-Azure-CI#1]
Hello, I am attempting to upload code using GitHub Actions, which works; however, I can't seem to get the volume mount to function properly. I believe the configuration files are automatically saved on the container, but I'm not certain. Could you assist me with this issue?

**Comment by dteck** [comment]
Hi,

I haven't used Github Actions to deploy to Azure before so I am not familiar with how that pipeline works. However, the way I have this configured it relies on using the ARM templates to set variables when deploying on Azure. The volume mount points inside the container are hard coded at build time (see the [image-mods.sh](https://github.com/dteck/Mediawiki-Azure-CI/blob/main/Image-mods.sh) file lines 11 to 14). And the Azure file shares to mount to the container are defined in the ARM template [Container-Instance-Registry.json](https://github.com/dteck/Mediawiki-Azure-CI/blob/main/ARM%20Deployment%20Scripts/Container-Instance-Registry.json) file. Lines 187 to 207 define the storage account file shares to use. While lines 154 to 163 point to the mountings we defined in image-mods.sh inside of the container.

There are no configuration files stored inside of the container. The container itself is intended to be stateless and sterile and all configuration happens as environmental variables for the container and for the wiki itself everything is defined by the LocalSettings.php file generated on first run that should be stored in one of the mounted volumes.  

you can read though the [wiki ](https://github.com/dteck/Mediawiki-Azure-CI/wiki)for this repo that discusses the steps of getting this running manually, and hopefully that will help you modify any code needed to get your pipelines set up.
https://github.com/dteck/Mediawiki-Azure-CI/wiki
